
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Z'Zince
 */
public class ManageStudentFrom extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudentFrom
     */
    Student std = new Student();
    DefaultTableModel model ;
    public ManageStudentFrom() {
        initComponents();
        std.fillStudentJtable(jTable1, "");
        ButtonGroup  bg = new ButtonGroup();
        bg.add(jRadioButtonMale);
        bg.add(jRadioButtonFemale);
        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);   //size field in table 
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.gray);  //set line table color 
        jTable1.setSelectionBackground(Color.RED);  //set color background select field

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_FName = new javax.swing.JTextField();
        jTextField_LName = new javax.swing.JTextField();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jTextField_Phone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jButton_AddStudent = new javax.swing.JButton();
        jButton_RemoveStudent = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Vall_find = new javax.swing.JTextField();
        jButton_EditStudent = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_STD_ID1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ManageStudent");

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("MANAGE STUDENTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(426, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(311, 311, 311))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setText("FIRST NAME  :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(50, 90, 90, 16);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("LAST NAME  :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 140, 84, 16);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setText("SEX  :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(100, 180, 35, 16);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setText("PHONE  :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(80, 230, 60, 16);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setText("ADDRESS  :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(70, 280, 70, 16);
        jPanel3.add(jTextField_FName);
        jTextField_FName.setBounds(180, 80, 220, 30);
        jPanel3.add(jTextField_LName);
        jTextField_LName.setBounds(180, 130, 220, 30);

        jRadioButtonMale.setText("MALE");
        jPanel3.add(jRadioButtonMale);
        jRadioButtonMale.setBounds(180, 180, 63, 21);

        jRadioButtonFemale.setText("FEMALE");
        jPanel3.add(jRadioButtonFemale);
        jRadioButtonFemale.setBounds(260, 180, 77, 21);

        jTextField_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneActionPerformed(evt);
            }
        });
        jTextField_Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhoneKeyTyped(evt);
            }
        });
        jPanel3.add(jTextField_Phone);
        jTextField_Phone.setBounds(180, 220, 220, 30);

        jTextArea_Address.setColumns(20);
        jTextArea_Address.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Address);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(180, 270, 220, 141);

        jButton_AddStudent.setText("ADD");
        jButton_AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddStudentActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_AddStudent);
        jButton_AddStudent.setBounds(310, 430, 85, 32);

        jButton_RemoveStudent.setText("REMOVE");
        jButton_RemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveStudentActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_RemoveStudent);
        jButton_RemoveStudent.setBounds(80, 430, 85, 32);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setText("ENTER VALUE TO SEARCH :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(470, 40, 170, 16);

        jTextField_Vall_find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Vall_findKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Vall_findKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Vall_findKeyTyped(evt);
            }
        });
        jPanel3.add(jTextField_Vall_find);
        jTextField_Vall_find.setBounds(670, 30, 330, 30);

        jButton_EditStudent.setText("EDIT");
        jButton_EditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditStudentActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_EditStudent);
        jButton_EditStudent.setBounds(200, 430, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Sex", "Phone Number", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(470, 84, 530, 380);

        jTextField_STD_ID1.setEditable(false);
        jPanel3.add(jTextField_STD_ID1);
        jTextField_STD_ID1.setBounds(180, 30, 220, 30);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel8.setText("ID :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(120, 40, 21, 16);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneActionPerformed

    
    private void jTextField_PhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneKeyTyped
        // Allow Only Number
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_PhoneKeyTyped

    private void jButton_AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddStudentActionPerformed

        AddStudentForm Addstd = new AddStudentForm();
        Addstd.setVisible(true);
        Addstd.pack();
        Addstd.setLocationRelativeTo(null);
        Addstd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  //close page add only
        
    }//GEN-LAST:event_jButton_AddStudentActionPerformed

    private void jButton_RemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveStudentActionPerformed
        //when delete student score all delete by constraint 
 
        if(jTextField_STD_ID1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No Student Selected.");
        }
        
        String id = jTextField_STD_ID1.getText();
        std.InsertUpdateDeleteStudent('d', id, null, null, null, null, null);
        std.fillStudentJtable(jTable1, "");
        jTable1.setModel(new DefaultTableModel(null , new Object[]{"ID","First Name","Last Name","Sex","Phone Number","Address"}));
        std.fillStudentJtable(jTable1, jTextField_Vall_find.getText());
        MainForm.jLabel_StdCount.setText("Students Count : " + Integer.toString(MyFunction.countData("student")));
        
        jTextField_STD_ID1.setText("");
        jTextArea_Address.setText("");
        jTextField_FName.setText("");
        jTextField_LName.setText("");
        jTextField_Phone.setText("");
        jRadioButtonMale.setSelected(false);
        jRadioButtonFemale.setSelected(false);
        
        
    }//GEN-LAST:event_jButton_RemoveStudentActionPerformed

    public boolean verifText()
    {
        if (jTextField_FName.getText().equals("") || jTextField_LName.getText().equals("") 
                || jTextField_Phone.getText().equals("") || jTextArea_Address.getText().equals("")
                || jTextField_STD_ID1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"One Or More Empty Field.");
            return false ;
        }
        else
        {
            return true ; 
        }
    }
    
    private void jButton_EditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditStudentActionPerformed
        
        
        String id = jTextField_STD_ID1.getText();
        String fname = jTextField_FName.getText();
        String lname = jTextField_LName.getText();
        String phone = jTextField_Phone.getText();
        String address = jTextArea_Address.getText();
        String sex = "";
        if(jRadioButtonFemale.isSelected())
        {
            sex = "Female";
        }
        else if (jRadioButtonFemale.isSelected())
        {
            sex = "Male";
        }
                   
        if (verifText())
        {
            Student std = new Student();
            std.InsertUpdateDeleteStudent('u', id, fname, lname, sex, phone, address);
            
        }
    }//GEN-LAST:event_jButton_EditStudentActionPerformed
    
    int rowIndex ;
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        rowIndex = jTable1.getSelectedRow();
        
        if (model.getValueAt(rowIndex, 3).toString().equals("Male"))
        {
            jRadioButtonMale.setSelected(true) ;
            jRadioButtonFemale.setSelected(false) ;
        }
        else
        {
            jRadioButtonFemale.setSelected(true) ;
            jRadioButtonMale.setSelected(false) ;
        }
        jTextField_STD_ID1.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField_FName.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField_LName.setText(model.getValueAt(rowIndex, 2).toString());
        jTextField_Phone.setText(model.getValueAt(rowIndex, 4).toString());
        jTextArea_Address.setText(model.getValueAt(rowIndex, 5).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_Vall_findKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Vall_findKeyTyped
        
    }//GEN-LAST:event_jTextField_Vall_findKeyTyped

    private void jTextField_Vall_findKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Vall_findKeyPressed
        
    }//GEN-LAST:event_jTextField_Vall_findKeyPressed

    private void jTextField_Vall_findKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Vall_findKeyReleased
        jTable1.setModel(new DefaultTableModel(null , new Object[]{"ID","First Name","Last Name","Sex","Phone Number","Address"}));
        std.fillStudentJtable(jTable1, jTextField_Vall_find.getText());
    }//GEN-LAST:event_jTextField_Vall_findKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        
        //slide key up down in keybored to data
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN )
        {
            rowIndex = jTable1.getSelectedRow();
            jTextField_STD_ID1.setText(model.getValueAt(rowIndex, 0).toString());
            jTextField_FName.setText(model.getValueAt(rowIndex, 1).toString());
            jTextField_LName.setText(model.getValueAt(rowIndex, 2).toString());
            jTextField_Phone.setText(model.getValueAt(rowIndex, 4).toString());
            jTextArea_Address.setText(model.getValueAt(rowIndex, 5).toString());
            
            if (model.getValueAt(rowIndex, 3).toString().equals("Male"))
            {
                jRadioButtonMale.setSelected(true) ;
                jRadioButtonFemale.setSelected(false) ;
            }
            else
            {
                jRadioButtonFemale.setSelected(true) ;
                jRadioButtonMale.setSelected(false) ;
            }
        }
        
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudentFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddStudent;
    private javax.swing.JButton jButton_EditStudent;
    private javax.swing.JButton jButton_RemoveStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_Address;
    private javax.swing.JTextField jTextField_FName;
    private javax.swing.JTextField jTextField_LName;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_STD_ID1;
    private javax.swing.JTextField jTextField_Vall_find;
    // End of variables declaration//GEN-END:variables
}
